
defaults: &defaults
  domain: "192.168.0.17:3000"
  email_server: "secure.emailsrvr.com"
  email_sender: 'test@onyx-international.com'
  email_password: '****'


development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
